version: "2.4"
services:
    detector_1:
        build:
            context: .
            dockerfile: Dockerfile

        environment:
            INTERVAL: ${INTERVAL:-0.3}
            PYTHONUNBUFFERED: 1
            NODE_NAME: ec-a-1
            ECCI_LOCAL_BROKER_IP: ${ECCI_LOCAL_BROKER_IP:-192.168.0.114}
            ECCI_LOCAL_BROKER_PORT: 1884
            ECCI_LOCAL_BROKER_ID: ec-a
            ECCI_APP_ID: experiment
            ECCI_CONTAINER_NAME: detector
            ECCI_REMOTE_BROKER_ID: ${ECCI_REMOTE_BROKER_ID:-321}
            SCENARIO: ${SCENARIO:-ACE+}
            METRIC: '${METRIC:-false}'
            COMPRESSED: '${COMPRESSED:-false}'
            COMPRESSED_QUALITY: '${COMPRESSED_QUALITY:-100}'
            VIDEOS: ${VIDEOS:-1min}
        volumes:
            - $PWD/videos/:/videos
            - $PWD/main.py:/main.py
            - $PWD/mqtt_client.py:/mqtt_client.py
        command: bash -c "python3 main.py"

    detector_2:
        build:
            context: .
            dockerfile: Dockerfile

        environment:
            INTERVAL: ${INTERVAL:-0.3}
            PYTHONUNBUFFERED: 1
            NODE_NAME: ec-a-2
            ECCI_LOCAL_BROKER_IP: ${ECCI_LOCAL_BROKER_IP:-192.168.0.114}
            ECCI_LOCAL_BROKER_PORT: 1884
            ECCI_LOCAL_BROKER_ID: ec-a
            ECCI_APP_ID: experiment
            ECCI_CONTAINER_NAME: detector
            ECCI_REMOTE_BROKER_ID: ${ECCI_REMOTE_BROKER_ID:-321}
            SCENARIO: ${SCENARIO:-ACE+}
            METRIC: '${METRIC:-false}'
            COMPRESSED: '${COMPRESSED:-false}'
            COMPRESSED_QUALITY: '${COMPRESSED_QUALITY:-100}'
            VIDEOS: ${VIDEOS:-1min}
        volumes:
            - $PWD/videos/:/videos
            - $PWD/main.py:/main.py
            - $PWD/mqtt_client.py:/mqtt_client.py
        command: bash -c "python3 main.py"

    detector_3:
        build:
            context: .
            dockerfile: Dockerfile

        environment:
            INTERVAL: ${INTERVAL:-0.3}
            PYTHONUNBUFFERED: 1
            NODE_NAME: ec-a-3
            ECCI_LOCAL_BROKER_IP: ${ECCI_LOCAL_BROKER_IP:-192.168.0.114}
            ECCI_LOCAL_BROKER_PORT: 1884
            ECCI_LOCAL_BROKER_ID: ec-a
            ECCI_APP_ID: experiment
            ECCI_CONTAINER_NAME: detector
            ECCI_REMOTE_BROKER_ID: ${ECCI_REMOTE_BROKER_ID:-321}
            SCENARIO: ${SCENARIO:-ACE+}
            METRIC: '${METRIC:-false}'
            COMPRESSED: '${COMPRESSED:-false}'
            COMPRESSED_QUALITY: '${COMPRESSED_QUALITY:-100}'
            VIDEOS: ${VIDEOS:-1min}
        volumes:
            - $PWD/videos/:/videos
            - $PWD/main.py:/main.py
            - $PWD/mqtt_client.py:/mqtt_client.py
        command: bash -c "python3 main.py"

    detector_4:
        build:
            context: .
            dockerfile: Dockerfile

        environment:
            INTERVAL: ${INTERVAL:-0.3}
            PYTHONUNBUFFERED: 1
            NODE_NAME: ec-b-1
            ECCI_LOCAL_BROKER_IP: ${ECCI_LOCAL_BROKER_IP:-192.168.0.114}
            ECCI_LOCAL_BROKER_PORT: 1885
            ECCI_LOCAL_BROKER_ID: ec-b
            ECCI_APP_ID: experiment
            ECCI_CONTAINER_NAME: detector
            ECCI_REMOTE_BROKER_ID: ${ECCI_REMOTE_BROKER_ID:-321}
            SCENARIO: ${SCENARIO:-ACE+}
            METRIC: '${METRIC:-false}'
            COMPRESSED: '${COMPRESSED:-false}'
            COMPRESSED_QUALITY: '${COMPRESSED_QUALITY:-100}'
            VIDEOS: ${VIDEOS:-1min}
        volumes:
            - $PWD/videos/:/videos
            - $PWD/main.py:/main.py
            - $PWD/mqtt_client.py:/mqtt_client.py
        command: bash -c "python3 main.py"

    detector_5:
        build:
            context: .
            dockerfile: Dockerfile

        environment:
            INTERVAL: ${INTERVAL:-0.3}
            PYTHONUNBUFFERED: 1
            NODE_NAME: ec-b-2
            ECCI_LOCAL_BROKER_IP: ${ECCI_LOCAL_BROKER_IP:-192.168.0.114}
            ECCI_LOCAL_BROKER_PORT: 1885
            ECCI_LOCAL_BROKER_ID: ec-b
            ECCI_APP_ID: experiment
            ECCI_CONTAINER_NAME: detector
            ECCI_REMOTE_BROKER_ID: ${ECCI_REMOTE_BROKER_ID:-321}
            SCENARIO: ${SCENARIO:-ACE+}
            METRIC: '${METRIC:-false}'
            COMPRESSED: '${COMPRESSED:-false}'
            COMPRESSED_QUALITY: '${COMPRESSED_QUALITY:-100}'
            VIDEOS: ${VIDEOS:-1min}
        volumes:
            - $PWD/videos/:/videos
            - $PWD/main.py:/main.py
            - $PWD/mqtt_client.py:/mqtt_client.py
        command: bash -c "python3 main.py"

    detector_6:
        build:
            context: .
            dockerfile: Dockerfile

        environment:
            INTERVAL: ${INTERVAL:-0.3}
            PYTHONUNBUFFERED: 1
            NODE_NAME: ec-b-3
            ECCI_LOCAL_BROKER_IP: ${ECCI_LOCAL_BROKER_IP:-192.168.0.114}
            ECCI_LOCAL_BROKER_PORT: 1885
            ECCI_LOCAL_BROKER_ID: ec-b
            ECCI_APP_ID: experiment
            ECCI_CONTAINER_NAME: detector
            ECCI_REMOTE_BROKER_ID: ${ECCI_REMOTE_BROKER_ID:-321}
            SCENARIO: ${SCENARIO:-ACE+}
            METRIC: '${METRIC:-false}'
            COMPRESSED: '${COMPRESSED:-false}'
            COMPRESSED_QUALITY: '${COMPRESSED_QUALITY:-100}'
            VIDEOS: ${VIDEOS:-1min}
        volumes:
            - $PWD/videos/:/videos
            - $PWD/main.py:/main.py
            - $PWD/mqtt_client.py:/mqtt_client.py
        command: bash -c "python3 main.py"

    detector_7:
        build:
            context: .
            dockerfile: Dockerfile

        environment:
            INTERVAL: ${INTERVAL:-0.3}
            PYTHONUNBUFFERED: 1
            NODE_NAME: ec-c-1
            ECCI_LOCAL_BROKER_IP: ${ECCI_LOCAL_BROKER_IP:-192.168.0.114}
            ECCI_LOCAL_BROKER_PORT: 1886
            ECCI_LOCAL_BROKER_ID: ec-c
            ECCI_APP_ID: experiment
            ECCI_CONTAINER_NAME: detector
            ECCI_REMOTE_BROKER_ID: ${ECCI_REMOTE_BROKER_ID:-321}
            SCENARIO: ${SCENARIO:-ACE+}
            METRIC: '${METRIC:-false}'
            COMPRESSED: '${COMPRESSED:-false}'
            COMPRESSED_QUALITY: '${COMPRESSED_QUALITY:-100}'
            VIDEOS: ${VIDEOS:-1min}
        volumes:
            - $PWD/videos/:/videos
            - $PWD/main.py:/main.py
            - $PWD/mqtt_client.py:/mqtt_client.py
        command: bash -c "python3 main.py"

    detector_8:
        build:
            context: .
            dockerfile: Dockerfile

        environment:
            INTERVAL: ${INTERVAL:-0.3}
            PYTHONUNBUFFERED: 1
            NODE_NAME: ec-c-2
            ECCI_LOCAL_BROKER_IP: ${ECCI_LOCAL_BROKER_IP:-192.168.0.114}
            ECCI_LOCAL_BROKER_PORT: 1886
            ECCI_LOCAL_BROKER_ID: ec-c
            ECCI_APP_ID: experiment
            ECCI_CONTAINER_NAME: detector
            ECCI_REMOTE_BROKER_ID: ${ECCI_REMOTE_BROKER_ID:-321}
            SCENARIO: ${SCENARIO:-ACE+}
            METRIC: '${METRIC:-false}'
            COMPRESSED: '${COMPRESSED:-false}'
            COMPRESSED_QUALITY: '${COMPRESSED_QUALITY:-100}'
            VIDEOS: ${VIDEOS:-1min}
        volumes:
            - $PWD/videos/:/videos
            - $PWD/main.py:/main.py
            - $PWD/mqtt_client.py:/mqtt_client.py
        command: bash -c "python3 main.py"

    detector_9:
        build:
            context: .
            dockerfile: Dockerfile

        environment:
            INTERVAL: ${INTERVAL:-0.3}
            PYTHONUNBUFFERED: 1
            NODE_NAME: ec-c-3
            ECCI_LOCAL_BROKER_IP: ${ECCI_LOCAL_BROKER_IP:-192.168.0.114}
            ECCI_LOCAL_BROKER_PORT: 1886
            ECCI_LOCAL_BROKER_ID: ec-c
            ECCI_APP_ID: experiment
            ECCI_CONTAINER_NAME: detector
            ECCI_REMOTE_BROKER_ID: ${ECCI_REMOTE_BROKER_ID:-321}
            SCENARIO: ${SCENARIO:-ACE+}
            METRIC: '${METRIC:-false}'
            COMPRESSED: '${COMPRESSED:-false}'
            COMPRESSED_QUALITY: '${COMPRESSED_QUALITY:-100}'
            VIDEOS: ${VIDEOS:-1min}
        volumes:
            - $PWD/videos/:/videos
            - $PWD/main.py:/main.py
            - $PWD/mqtt_client.py:/mqtt_client.py
        command: bash -c "python3 main.py"
