version: "2.4"
services:
    detector:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: detector

        environment:
            INTERVAL:  ${INTERVAL:-0.3}
            PYTHONUNBUFFERED: 1
            NODE_NAME: ${NODE_NAME:-1}
            ECCI_LOCAL_BROKER_IP: ${ECCI_LOCAL_BROKER_IP:-192.168.0.117}
            ECCI_LOCAL_BROKER_PORT: 1883
            ECCI_LOCAL_BROKER_ID: ${ECCI_LOCAL_BROKER_ID:-123}
            ECCI_APP_ID: experiment
            ECCI_CONTAINER_NAME: detector
            ECCI_REMOTE_BROKER_ID: ${ECCI_REMOTE_BROKER_ID:-321}
            SCENARIO: ${SCENARIO:-ACE+}
            METRIC: '${METRIC:-false}'
            COMPRESSED: '${COMPRESSED:-false}'
            COMPRESSED_QUALITY: '${COMPRESSED_QUALITY:-100}'
            VIDEOS: ${VIDEOS:-1min}
        volumes:
            - $PWD/videos/:/videos
            - $PWD/main.py:/main.py
            - $PWD/mqtt_client.py:/mqtt_client.py
        command: bash -c "python3 main.py"
        cpus: 2