version: "2.4"
services:
    scheduler:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: scheduler

        environment:
            PYTHONUNBUFFERED: 1
            NODE_NAME: ${NODE_NAME:-1}
            ECCI_LOCAL_BROKER_IP: ${ECCI_LOCAL_BROKER_IP:-192.168.0.117}
            ECCI_LOCAL_BROKER_PORT: 1883
            ECCI_LOCAL_BROKER_ID: ${ECCI_LOCAL_BROKER_ID:-123}
            ECCI_APP_ID: experiment
            ECCI_CONTAINER_NAME: scheduler
            INTERVAL:  ${INTERVAL:-0.3}
        volumes:
            - $PWD/main.py:/main.py
            - $PWD/mqtt_client.py:/mqtt_client.py
        command: bash -c "python3 main.py"